{"1": "google.com"}
{"2": "in.gr"}
{"3": "youtube.com"}
{"4": "google.gr"}
{"5": "enimerotiko.gr"}
{"6": "lifo.gr"}
{"7": "dikaiologitika.gr"}
{"8": "gsis.gr"}
{"9": "zougla.gr"}
{"10": "i-diakopes.gr"}
{"11": "aftodioikisi.gr"}
{"12": "to10.gr"}
{"13": "skroutz.gr"}
{"14": "alfavita.gr"}
{"15": "yahoo.com"}
{"16": "services.gov.gr"}
{"17": "pronews.gr"}
{"18": "protothema.gr"}
{"19": "naftemporiki.gr"}
{"20": "typosthes.gr"}
{"21": "winbank.gr"}
{"22": "pagenews.gr"}
{"23": "aade.gr"}
{"24": "newsauto.gr"}
{"25": "tanea.gr"}
{"26": "thebest.gr"}
{"27": "nbg.gr"}
{"28": "epirusonline.gr"}
{"29": "sch.gr"}
{"30": "www.gov.gr"}
{"31": "wikipedia.org"}
{"32": "tovima.gr"}
{"33": "diaforetiko.gr"}
{"34": "parapolitika.gr"}
{"35": "xhamster.com"}
{"36": "tomanifesto.gr"}
{"37": "bongacams.com"}
{"38": "xrysessyntages.gr"}
{"39": "newsbreak.gr"}
{"40": "live.com"}
{"41": "tainio-mania.online"}
{"42": "newpost.gr"}
{"43": "newsit.gr"}
{"44": "meteo.gr"}
{"45": "thestival.gr"}
{"46": "liberal.gr"}
{"47": "netflix.com"}
{"48": "espressonews.gr"}
{"49": "larissanet.gr"}
{"50": "autogreeknews.gr"}
