{"1": "google.com"}
{"2": "youtube.com"}
{"3": "google.pl"}
{"4": "allegro.pl"}
{"5": "onet.pl"}
{"6": "wp.pl"}
{"7": "olx.pl"}
{"8": "interia.pl"}
{"9": "facebook.com"}
{"10": "bongacams.com"}
{"11": "wikipedia.org"}
{"12": "netflix.com"}
{"13": "cda.pl"}
{"14": "o2.pl"}
{"15": "otomoto.pl"}
{"16": "gazeta.pl"}
{"17": "joemonster.org"}
{"18": "microsoft.com"}
{"19": "wykop.pl"}
{"20": "librus.pl"}
{"21": "rezka.ag"}
{"22": "centrum24.pl"}
{"23": "vulcan.net.pl"}
{"24": "microsoftonline.com"}
{"25": "yahoo.com"}
{"26": "tvp.pl"}
{"27": "chaturbate.com"}
{"28": "filmweb.pl"}
{"29": "start-pl.com"}
{"30": "teleman.pl"}
{"31": "www.gov.pl"}
{"32": "ceneo.pl"}
{"33": "demotywatory.pl"}
{"34": "pz.gov.pl"}
{"35": "ipko.pl"}
{"36": "mbank.pl"}
{"37": "login.gov.pl"}
{"38": "pudelek.pl"}
{"39": "roblox.com"}
{"40": "medonet.pl"}
{"41": "vk.com"}
{"42": "kwejk.pl"}
{"43": "kinokrad.co"}
{"44": "money.pl"}
{"45": "chess.com"}
{"46": "mediaexpert.pl"}
{"47": "bankmillennium.pl"}
{"48": "businessinsider.com.pl"}
{"49": "zoom.us"}
{"50": "aliexpress.com"}
