{"1": "google.com"}
{"2": "youtube.com"}
{"3": "google.de"}
{"4": "amazon.de"}
{"5": "ebay.de"}
{"6": "wikipedia.org"}
{"7": "web.de"}
{"8": "gmx.net"}
{"9": "ebay-kleinanzeigen.de"}
{"10": "t-online.de"}
{"11": "facebook.com"}
{"12": "xhamster.com"}
{"13": "bongacams.com"}
{"14": "mail.ru"}
{"15": "vk.com"}
{"16": "live.com"}
{"17": "bing.com"}
{"18": "ok.ru"}
{"19": "chaturbate.com"}
{"20": "yahoo.com"}
{"21": "netflix.com"}
{"22": "yandex.ru"}
{"23": "msn.com"}
{"24": "aparat.com"}
{"25": "pornhub.com"}
{"26": "microsoft.com"}
{"27": "telewebion.com"}
{"28": "chip.de"}
{"29": "zdf.de"}
{"30": "twitch.tv"}
{"31": "bild.de"}
{"32": "reddit.com"}
{"33": "otto.de"}
{"34": "rokna.net"}
{"35": "idealo.de"}
{"36": "varzesh3.com"}
{"37": "telekom.com"}
{"38": "xvideos.com"}
{"39": "filmix.ac"}
{"40": "namasha.com"}
{"41": "wetter.com"}
{"42": "donya-e-eqtesad.com"}
{"43": "n-tv.de"}
{"44": "delgarm.com"}
{"45": "ikea.com"}
{"46": "zoom.us"}
{"47": "paypal.com"}
{"48": "dhl.de"}
{"49": "pinterest.de"}
{"50": "ninisite.com"}
